name: AI Assisted CI/CD Pipeline

permissions:
  contents: write

on:
  push:
    branches:
      - main

    paths-ignore:
      - 'k8s/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Run Application Test
      run: |
        python -m py_compile app/app.py

    - name: AI Validation
      run: |
        echo "Running AI Code Validation"
        echo "Checking code quality"

    - name: Security Scan using Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ai-devops-app:${{ github.sha }} ./app

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/ai-devops-app:${{ github.sha }}

    - name: Update Kubernetes Deployment
      run: |
        sed -i 's|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/ai-devops-app:${{ github.sha }}|g' k8s/deployment.yaml

    - name: Commit and Push Changes
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "github-actions"

        git add k8s/deployment.yaml

        git commit -m "Updated image version" || echo "No changes"

        git push
